<h1>Round Table Plan</h1>

<script>
var flagWidth = 40
var flagHeight = 20 // used for approximation
var tableRadius = 100

function pullAndDisplayFlags () {
    $.ajax({
        type: "GET",
        url: "round-table/countries.json" + "?random=" + $('#seatCount').val(),
        dataType: "json"
        }).done(function (res) {
            displayFlags(res);
        }).fail(function (jqXHR, textStatus, errorThrown) {
            alert('Failed to pull countries')
            console.log("AJAX call failed: " + textStatus + ", " + errorThrown);
        });
}

function findOppositeCountry (index, allRecords) {
    // Find the corresponding index that is opposite to the given index. 
    var pos
    const middlePoint = allRecords.length / 2
    if (index < middlePoint) {
        pos = middlePoint + index
    } else {
        pos = index - middlePoint
    }
    return allRecords[pos]
}

function placeFlag (countryRecord, index, allRecords) {
    function showInfo () {
        var opposite = findOppositeCountry(index, allRecords)
        var text = countryRecord.name + ' sits opposite to ' + opposite.name
        window.alert(text)
    }

    var x
    var y

    var tableX = 200
    var tableY = 200

    var points = allRecords.length
    var denominator = points / 2

    // Use this as r for the calculation below
    var distanceFromCenter = tableRadius + flagWidth + 5

    // To get points for a circle, (x, y) positions are calcualted as:
    // x = r * cos(radians)
    // y = r * sin(radians)
    x = distanceFromCenter * Math.cos((index * Math.PI) / denominator)
    y = distanceFromCenter * Math.sin((index * Math.PI) / denominator)       
    

    var flagX = tableX + x - (flagWidth / 2)
    var flagY = tableY + y - (flagHeight / 2)
    var $flag = $('<img>')
    $flag
        .css({
            position: 'absolute',
            left: flagX + 'px',
            top: flagY + 'px',
            width: flagWidth,
            // height will be selected proportionally
        })
        .attr('src', countryRecord.flagUrl)
        .attr('title', countryRecord.alpha2)
        .attr('class', 'mini-flag')
        .click(showInfo)

    $('.flag-positioning').append($flag)
}

function placeAllFlags () {
    // remove existing flags
    $('.flag-positioning').empty();
    $('#error-box').html('')


    // Check that the input is a valid number and is even
    var seatCount = parseInt($('#seatCount').val())
    if (!Number.isFinite(seatCount)) {
        $('#error-box').append('Not a number')
        return false;
    } else if (seatCount != 0 && seatCount % 2 != 0) {
        $('#error-box').append('Not an even number')
        return false;
    }

    pullAndDisplayFlags()
}

function displayFlags (selectedCountries) {
    for (var i = 0; i < selectedCountries.length; i++) {
        var countryRecord = selectedCountries[i]
        placeFlag(countryRecord, i, selectedCountries)
    }
}

</script>

<form>
    Seats: <input value="4" id="seatCount" />
    <button type="button" onclick="placeAllFlags()">place</button>
    <div id='error-box' style='color: red; padding-left: 50px;'></div>
</form>

<div class="meeting-room">
    <img src="/round-table.png" class="round-table" />
    <div class="flag-positioning" />
</div>
