<script>
    function validate () {
        $('#error-box').html('')
        if ($('input[type=radio]:checked').length > 0) {
            return true
        }
        $('#error-box').append('Please select one of the options above.')
        return false;
    }
</script>
<div>
    Here is the flag:
</div>
<div class="flag-container">
    <img
        class="flag"
        src="<?= $country->getFlagUrl(); ?>"
        title="<?= $country->alpha2; ?>"
    />
</div>
<form method="POST" onsubmit="return validate();">
    <input type="hidden" name="country" value="<?= $country->alpha2 ?>">
    <p>Pick the right country out of <b><?= count($answers) ?></b> variants:</p>
    <ul class="answer-list">
    <?
        foreach ($answers as $answerCountry) {
            $alpha2 = $answerCountry->alpha2;
            echo '<li>';
            echo '<input type="radio" name="answer" id="answer-' . $alpha2 .'" value="' . $alpha2 . '" />';
            echo '<label for="answer-' . $alpha2 . '">';
            echo $answerCountry->name;
            echo " (", $answerCountry->alpha2, ")";
            echo '</label>';
            echo '</li>';
        }
    ?>
    </ul>
    <input type="submit" />
    <div id='error-box' style='color: red;'></div>
</form>
